In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from collections import Counter # help us perform voting when selecting most common class label
import pandas as pd
from sklearn.metrics import accuracy_score

from sklearn.tree import DecisionTreeClassifier

In [2]:
titanic=sns.load_dataset("titanic")

In [3]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [4]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [5]:
median_imputer=SimpleImputer(strategy="median")
titanic[["age"]]=median_imputer.fit_transform(titanic[["age"]])

most_frequent_imputer=SimpleImputer(strategy="most_frequent")
titanic[["embarked"]]=most_frequent_imputer.fit_transform(titanic[["embarked"]])

In [6]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [7]:
label_encoder=LabelEncoder()

titanic["sex"]=label_encoder.fit_transform(titanic["sex"])
titanic["embarked"]=label_encoder.fit_transform(titanic["embarked"])

In [8]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,Third,man,True,NaN,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,0,First,woman,False,C,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,2,Third,woman,False,NaN,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,2,First,woman,False,C,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,2,Third,man,True,NaN,Southampton,no,True


In [9]:
features=["pclass","sex","age","fare","embarked"]
target=["survived"]

In [10]:
X=titanic[features].values
y=titanic["survived"].values

In [13]:
X

array([[ 3.    ,  1.    , 22.    ,  7.25  ,  2.    ],
       [ 1.    ,  0.    , 38.    , 71.2833,  0.    ],
       [ 3.    ,  0.    , 26.    ,  7.925 ,  2.    ],
       ...,
       [ 3.    ,  0.    , 28.    , 23.45  ,  2.    ],
       [ 1.    ,  1.    , 26.    , 30.    ,  0.    ],
       [ 3.    ,  1.    , 32.    ,  7.75  ,  1.    ]])

In [15]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [16]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 5)
(179, 5)
(712,)
(179,)


In [19]:
X_train

array([[  1.    ,   1.    ,  45.5   ,  28.5   ,   2.    ],
       [  2.    ,   1.    ,  23.    ,  13.    ,   2.    ],
       [  3.    ,   1.    ,  32.    ,   7.925 ,   2.    ],
       ...,
       [  3.    ,   1.    ,  41.    ,  14.1083,   2.    ],
       [  1.    ,   0.    ,  14.    , 120.    ,   2.    ],
       [  1.    ,   1.    ,  21.    ,  77.2875,   2.    ]])

In [20]:
X_test

array([[  3.    ,   1.    ,  28.    ,  15.2458,   0.    ],
       [  2.    ,   1.    ,  31.    ,  10.5   ,   2.    ],
       [  3.    ,   1.    ,  20.    ,   7.925 ,   2.    ],
       [  2.    ,   0.    ,   6.    ,  33.    ,   2.    ],
       [  3.    ,   0.    ,  14.    ,  11.2417,   0.    ],
       [  1.    ,   0.    ,  26.    ,  78.85  ,   2.    ],
       [  3.    ,   0.    ,  28.    ,   7.75  ,   1.    ],
       [  3.    ,   1.    ,  16.    ,  18.    ,   2.    ],
       [  3.    ,   0.    ,  16.    ,   7.75  ,   1.    ],
       [  1.    ,   0.    ,  19.    ,  26.2833,   2.    ],
       [  1.    ,   1.    ,  37.    ,  53.1   ,   2.    ],
       [  3.    ,   1.    ,  44.    ,   8.05  ,   2.    ],
       [  3.    ,   0.    ,  28.    ,  25.4667,   2.    ],
       [  3.    ,   1.    ,  30.    ,   7.225 ,   0.    ],
       [  2.    ,   1.    ,  36.    ,  13.    ,   2.    ],
       [  1.    ,   0.    ,  16.    ,  39.4   ,   2.    ],
       [  1.    ,   1.    ,  42.    ,  52.5542,   2.    

In [21]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,

In [22]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1])

In [23]:
# We are using the OOPs Programming approach
# We will create a node for our Decision Tree model
# Each node in a decision tree can either be a decision node or a leaf node

class Node:
    def __init__(self,left=None,right=None,gain=None,value=None,feature_idx=None,threshold=None):

        # For a decision node
        self.feature_idx=feature_idx # stores the index of the feature we choose to split on
        self.threshold=threshold
        self.gain=gain # stores the value of information gain which ultimately determines the feature we choose to split on
        self.left=left # left child node of the parent node
        self.right=right # right child node of the parent node

        # For a leaf node it will only store the final value of the class it has converged to
        self.value=value


In [40]:
# DecisionTreeClassifier class to find the best split and make predcition

class DecisionTree:
    def __init__(self,min_samples_split=2,max_depth=5):

        self.root=None

        self.max_depth=max_depth
        self.min_samples_split=min_samples_split


        self.feature_importances_=None

    # recursive function that takes the dataset as input for the current node
    def build_tree(self,dataset,current_depth=0):
        X,y=dataset[:,:-1],dataset[:,-1]

        n_samples,n_features=X.shape

        if n_samples >= self.min_samples_split and current_depth <= self.max_depth:
            best_split=self.best_split(dataset,n_features)

            if best_split["gain"] > 0 and len(best_split)>0:
                left_node=self.build_tree(best_split["left_dataset"],current_depth+1)
                right_node=self.build_tree(best_split["right_dataset"],current_depth+1)

                return Node(left=left_node,right=right_node,gain=best_split["gain"],feature_idx=best_split["feature_idx"],threshold=best_split["threshold"])
                        

        leaf_value=Counter(y).most_common(1)[0][0]
        return Node(value=leaf_value)

    def best_split(self,dataset,n_features):
        best_split={"feature_idx":None,
                    "threshold":None,
                    "gain":-float("inf"),
                    "left_dataset":None,
                    "right_dataset":None}

        for feature_idx in range(n_features):
            feature_values=dataset[:,feature_idx]
            unique_values=np.unique(feature_values)

            thresholds=(
                unique_values[:-1]+unique_values[1:]
            )/2


            for threshold in thresholds:
                left_dataset,right_dataset=self.split(dataset,feature_idx,threshold)

                if len(left_dataset) and len(right_dataset):
                    parent_y,left_y,right_y=dataset[:,-1],left_dataset[:,-1],right_dataset[:,-1]

                    gain=self.gini_gain(parent_y,left_y,right_y)

                    if gain > best_split["gain"]:
                        best_split["feature_idx"]=feature_idx
                        best_split["threshold"]=threshold
                        best_split["gain"]=gain
                        best_split["left_dataset"]=left_dataset
                        best_split["right_dataset"]=right_dataset

        return best_split


    def split(self,dataset,feature_idx,threshold):
        left_dataset=np.array([row for row in dataset if row[feature_idx] <= threshold])
        right_dataset=np.array([row for row in dataset if row[feature_idx] > threshold])

        return left_dataset,right_dataset


    def gini_gain(self,parent_y,left_y,right_y):
        left_weight=len(left_y)/len(parent_y)
        right_weight=len(right_y)/len(parent_y)


        gain=self.gini(parent_y) - (left_weight * self.gini(left_y) + right_weight * self.gini(right_y))

        return gain


    def gini(self,y):
        impurity=1

        class_labels=np.unique(y)
        for class_label in class_labels:
            p=np.sum(y==class_label)/len(y)
            impurity-=p**2

        return impurity


    def fit(self, X, y):
        dataset = np.concatenate((X, y.reshape(-1, 1)), axis=1)
        self.root = self.build_tree(dataset)

    def predict(self, X):    
        predictions = [self.predict_class(row, self.root) for row in X]
        return np.array(predictions)


    def predict_class(self,row,node):
        if node.value!=None:
            return node.value

        feature_value=row[node.feature_idx]
        if feature_value<=node.threshold:
            return self.predict_class(row,node.left)
        else:
            return self.predict_class(row,node.right)


    def print_tree(self,node=None,indent=" "):
        if node is None:
            node=self.root

        if node.value is not None:
            print(indent,"Leaf:",node.value)
            return

        print(indent,f"X[{node.feature_idx}] <= {node.threshold: .3f}")

        self.print_tree(node.left,indent + indent)

        self.print_tree(node.right,indent+indent)

In [56]:
decision_tree_model=DecisionTree(min_samples_split=5,max_depth=5)
decision_tree_model.fit(X_train,y_train)

predictions=decision_tree_model.predict(X_test)

accuracy=accuracy_score(y_test,predictions)
print(f"Accuracy: {accuracy*100:.2f} %")

Accuracy: 80.45 %


In [42]:
decision_tree_model.print_tree()

  X[1] <=  0.500
   X[0] <=  2.500
     X[2] <=  2.500
         Leaf: 1.0
         X[2] <=  27.500
                 X[2] <=  24.500
                                 X[3] <=  13.396
                                                                 Leaf: 1.0
                                                                 Leaf: 1.0
                                 X[0] <=  1.500
                                                                 Leaf: 0.0
                                                                 Leaf: 1.0
                 X[2] <=  49.500
                                 Leaf: 1.0
                                 X[2] <=  50.500
                                                                 Leaf: 1.0
                                                                 Leaf: 1.0
     X[3] <=  23.350
         X[4] <=  1.500
                 X[3] <=  15.373
                                 X[3] <=  13.935
                                                                 Leaf

In [43]:
decision_tree_classifier=DecisionTreeClassifier(
    criterion="gini",
    max_depth=5,
    random_state=42)

decision_tree_classifier.fit(X_train,y_train)

decision_tree_prediction=decision_tree_classifier.predict(X_test)


print("Sklearn model accuracy:",round(accuracy_score(y_test,decision_tree_prediction)*100,2),"%")

                                                     

Sklearn model accuracy: 79.89 %


In [46]:
ccp_alphas=decision_tree_classifier.cost_complexity_pruning_path(X_train,y_train).ccp_alphas


In [47]:
ccp_alphas

array([0.        , 0.00014088, 0.00058521, 0.00081236, 0.00107253,
       0.00130996, 0.00133761, 0.00211232, 0.00258112, 0.00269413,
       0.0030052 , 0.00314046, 0.0033041 , 0.00547434, 0.0090554 ,
       0.01392951, 0.01592416, 0.03860535, 0.13777998])